version: '3.8'

services:
  # =========================
  # 1. Base de Datos PostgreSQL
  # =========================
  db:
    image: postgres:15-alpine
    container_name: postgres_gestionIES
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # =========================
  # 2. Backend - Node.js
  # =========================
  backend_app:
    build:
      context: https://github.com/Chisco77/gestionIES.git#main
      dockerfile: backend/Dockerfile
    image: gestionies_backend_app:latest
    container_name: node_gestionIES
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5000
      NODE_ENV: production
    depends_on:
      - db
    volumes:
      # Volumen persistente para uploads del backend
      - ./backend/uploads:/app/uploads

  # =========================
  # 3. Frontend / Nginx
  # =========================
  frontend_nginx:
    build:
      context: https://github.com/Chisco77/gestionIES.git#main
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_SERVER_URL: ${VITE_SERVER_URL}
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_IES_NAME: ${VITE_IES_NAME}
        VITE_DIRECCION_LINEA_1: ${VITE_DIRECCION_LINEA_1}
        VITE_DIRECCION_LINEA_2: ${VITE_DIRECCION_LINEA_2}
        VITE_DIRECCION_LINEA_3: ${VITE_DIRECCION_LINEA_3}
        VITE_DIRECCION_LINEA_4: ${VITE_DIRECCION_LINEA_4}
        VITE_DIRECCION_LINEA_5: ${VITE_DIRECCION_LINEA_5}
    container_name: nginx_gestionIES
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend_app
    volumes:
      # Certificados SSL proporcionados por el admin
      - /etc/nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - /etc/nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro
      # Configuración Nginx legacy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # PUBLIC PERSONALIZADO POR CENTRO - logos y planos
      - ./public:/usr/share/nginx/html/gestionIES/public:ro      
      # Carpeta de imágenes de alumnos
      - ./backend/uploads/alumnos:/app/backend/uploads/alumnos:ro
      # Dietas xls
      - ./backend/DIETAS.xlsx:/app/backend

volumes:
  postgres_data:
